---

- hosts: webservers
  user: ubuntu
  sudo: True


  vars:
    app_name: vimrc_configuration
    home_directory: /home/ubuntu
    vimrc_repo_url: https://github.com/hljyunxi/my_vimrc
    vim_vbundle_repo_url: https://github.com/gmarik/vundle.git 
    vim_powerline_repo_url: https://github.com/Lokaltog/vim-powerline
    vim_golang_repo_url: https://github.com/jnwhiteh/vim-golang.git
    vim_nerdtree_repo_url: https://github.com/scrooloose/nerdtree.git
    vim_molokai_repo_url: https://github.com/tomasr/molokai


  tasks:
    - name: install needed pakages
      action: apt pkg=$item state=installed
      with_items:
        - vim

    - name: download vimrc from git
      action: git repo=$vimrc_repo_url dest=$home_directory/my_vimrc
   
    - name: cp .vimrc
      action: command cp $home_directory/my_vimrc/vimrc $home_directory/.vimrc

    - name: mkidr vim bundle
      action: file dest=$home_directory/.vim/bundle state=directory

    - name: install vbundle 
      action: git repo=$vim_vbundle_repo_url dest=$home_directory/.vim/bundle/vbundle

    - name: install bundle vim_powerline
      action: git repo=$vim_powerline_repo_url dest=$home_directory/.vim/bundle/vim-powerline

    - name: install bundle vim_golang
      action: git repo=$vim_golang_repo_url dest=$home_directory/.vim/bundle/vim-golang

    - name: install bundle vim_nerdtree
      action: git repo=$vim_nerdtree_repo_url dest=$home_directory/.vim/bundle/nerdtree

    - name: install bundle vim_molokai
      action: git repo=$vim_molokai_repo_url dest=$home_directory/.vim/bundle/molokai
