- name: install nginx 
  action: apt pkg=nginx state=installed

- name: Ensure main Nginx configuration file is up to date
  template: src=templates/nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Ensure Nginx does not have a default configuration
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
